// AUTO-GENERATED by scripts/generate-ffi.ts — DO NOT EDIT
// Source: target/moontui-schema.json

import { dirname, join } from "node:path";
import { backend, FFIType, ffiBool, type Pointer } from "./platform/index";
import { type RGBAInput, toRGBA } from "./rgba";

export type { Pointer } from "./platform/index";

function getLibraryName(): string {
  const platform = process.platform;
  switch (platform) {
    case "win32":
      return "moontui_core.dll";
    case "darwin":
      return "libmoontui_core.dylib";
    case "linux":
      return "libmoontui_core.so";
    default:
      throw new Error(`Unsupported platform: ${platform}`);
  }
}

function resolveLibPath(): string {
  const platform = process.platform;
  const arch = process.arch;
  const packageName = `@moontui/core-${platform}-${arch}`;
  try {
    const resolved = import.meta.resolve(`${packageName}/index.js`);
    const dir = dirname(backend.resolveURL(resolved));
    return join(dir, getLibraryName());
  } catch {
    throw new Error(
      `moontui is not supported on the current platform: ${platform}-${arch}. ` +
        "Please ensure you are using a supported platform (Darwin x64/arm64, Linux x64/arm64, Windows x64)."
    );
  }
}

const libPath = resolveLibPath();

// biome-ignore lint/complexity/noBannedTypes: opaque handle type for FFI branding
export type Renderer = {};
// biome-ignore lint/complexity/noBannedTypes: opaque handle type for FFI branding
export type Buffer = {};

function toPointer<T>(value: number | bigint): Pointer<T> {
  return backend.toPointer<T>(value);
}

function normalizeU64(value: number | bigint): bigint {
  return typeof value === "bigint" ? value : BigInt(value);
}

const lib = backend.loadLibrary(libPath, {
  // --- Manual FFI functions (/// @ffi_manual) ---
  bufferDrawBox: {
    args: [
      FFIType.ptr,
      FFIType.i32,
      FFIType.i32,
      FFIType.u32,
      FFIType.u32,
      FFIType.ptr,
      FFIType.u32,
      FFIType.ptr,
      FFIType.ptr,
    ],
    returns: FFIType.void,
  },
  bufferDrawChar: {
    args: [
      FFIType.ptr,
      FFIType.u32,
      FFIType.u32,
      FFIType.u32,
      FFIType.ptr,
      FFIType.ptr,
      FFIType.u32,
    ],
    returns: FFIType.void,
  },
  bufferDrawText: {
    args: [
      FFIType.ptr,
      FFIType.ptr,
      FFIType.u64,
      FFIType.u32,
      FFIType.u32,
      FFIType.ptr,
      FFIType.ptr,
      FFIType.u32,
    ],
    returns: FFIType.void,
  },
  bufferFillRect: {
    args: [
      FFIType.ptr,
      FFIType.u32,
      FFIType.u32,
      FFIType.u32,
      FFIType.u32,
      FFIType.ptr,
    ],
    returns: FFIType.void,
  },
  bufferWriteResolvedChars: {
    args: [FFIType.ptr, FFIType.ptr, FFIType.u64, FFIType.bool],
    returns: FFIType.u32,
  },
  bufferClear: { args: [FFIType.ptr, FFIType.ptr], returns: FFIType.void },
  createRenderer: {
    args: [FFIType.u32, FFIType.u32, FFIType.bool],
    returns: FFIType.ptr,
  },
  destroyRenderer: { args: [FFIType.ptr], returns: FFIType.i32 },
  getCapabilities: { args: [FFIType.ptr, FFIType.ptr], returns: FFIType.void },
  getCapturedOutput: { args: [FFIType.ptr, FFIType.ptr], returns: FFIType.ptr },
  getCurrentBuffer: { args: [FFIType.ptr], returns: FFIType.ptr },
  getNextBuffer: { args: [FFIType.ptr], returns: FFIType.ptr },
  getRenderStats: { args: [FFIType.ptr, FFIType.ptr], returns: FFIType.void },
  getTerminalSize: { args: [], returns: FFIType.u64 },
  injectMouseEvent: {
    args: [
      FFIType.ptr,
      FFIType.ptr,
      FFIType.u64,
      FFIType.u32,
      FFIType.u32,
      FFIType.u32,
      FFIType.bool,
      FFIType.bool,
      FFIType.bool,
      FFIType.u32,
    ],
    returns: FFIType.void,
  },
  injectResizeEvent: {
    args: [FFIType.ptr, FFIType.u32, FFIType.u32],
    returns: FFIType.void,
  },
  render: { args: [FFIType.ptr, FFIType.bool], returns: FFIType.i32 },
  restoreTerminal: { args: [FFIType.ptr], returns: FFIType.i32 },
  setupTerminal: {
    args: [FFIType.ptr, FFIType.bool, FFIType.bool, FFIType.bool],
    returns: FFIType.i32,
  },
  // --- OptimizedBuffer ---
  bufferCellAttributes: {
    args: [FFIType.ptr, FFIType.u64],
    returns: FFIType.u32,
  },
  bufferCellChar: { args: [FFIType.ptr, FFIType.u64], returns: FFIType.u32 },
  bufferCellsLen: { args: [FFIType.ptr], returns: FFIType.u64 },
  bufferGetAttributesPtr: { args: [FFIType.ptr], returns: FFIType.ptr },
  bufferGetBgPtr: { args: [FFIType.ptr], returns: FFIType.ptr },
  bufferGetCharPtr: { args: [FFIType.ptr], returns: FFIType.ptr },
  bufferGetFgPtr: { args: [FFIType.ptr], returns: FFIType.ptr },
  bufferRealCharSize: {
    args: [FFIType.ptr, FFIType.bool],
    returns: FFIType.u32,
  },

  // --- CliRenderer ---
  clearOutput: { args: [FFIType.ptr], returns: FFIType.void },
  disableMouse: { args: [FFIType.ptr], returns: FFIType.void },
  enableMouse: { args: [FFIType.ptr, FFIType.bool], returns: FFIType.void },
  getMousePointerStyle: { args: [FFIType.ptr], returns: FFIType.ptr },
  height: { args: [FFIType.ptr], returns: FFIType.u32 },
  hitGridAdd: {
    args: [
      FFIType.ptr,
      FFIType.u32,
      FFIType.u32,
      FFIType.u32,
      FFIType.u32,
      FFIType.u32,
    ],
    returns: FFIType.void,
  },
  hitGridCheckHit: {
    args: [FFIType.ptr, FFIType.u32, FFIType.u32],
    returns: FFIType.u32,
  },
  hitGridClear: { args: [FFIType.ptr], returns: FFIType.void },
  hitGridClearDirty: { args: [FFIType.ptr], returns: FFIType.void },
  hitGridClearScissorRects: { args: [FFIType.ptr], returns: FFIType.void },
  hitGridIsDirty: { args: [FFIType.ptr], returns: FFIType.bool },
  hitGridPopScissorRect: { args: [FFIType.ptr], returns: FFIType.void },
  hitGridPushScissorRect: {
    args: [FFIType.ptr, FFIType.u32, FFIType.u32, FFIType.u32, FFIType.u32],
    returns: FFIType.void,
  },
  processEvents: { args: [FFIType.ptr], returns: FFIType.u64 },
  resizeRenderer: {
    args: [FFIType.ptr, FFIType.u32, FFIType.u32],
    returns: FFIType.void,
  },
  setCursorPosition: {
    args: [FFIType.ptr, FFIType.i32, FFIType.i32, FFIType.bool],
    returns: FFIType.void,
  },
  setEventCallback: { args: [FFIType.ptr, FFIType.ptr], returns: FFIType.void },
  setMouseCallback: { args: [FFIType.ptr, FFIType.ptr], returns: FFIType.void },
  setMousePointerStyle: {
    args: [FFIType.ptr, FFIType.ptr],
    returns: FFIType.void,
  },
  setResizeCallback: {
    args: [FFIType.ptr, FFIType.ptr],
    returns: FFIType.void,
  },
  width: { args: [FFIType.ptr], returns: FFIType.u32 },
});

const textEncoder = new TextEncoder();

function rgbaPtr(color: RGBAInput): Pointer<void> {
  const rgba = toRGBA(color);
  return backend.ptr(rgba.buffer);
}

// Categorize functions into sub-groups
export const api = {
  buffer: {
    bufferCellAttributes(p: Pointer<Buffer>, idx: number): number {
      return lib.symbols.bufferCellAttributes(p, idx);
    },
    bufferCellChar(p: Pointer<Buffer>, idx: number): number {
      return lib.symbols.bufferCellChar(p, idx);
    },
    bufferCellsLen(p: Pointer<Buffer>): number {
      return lib.symbols.bufferCellsLen(p);
    },
    bufferGetAttributesPtr(p: Pointer<Buffer>): Pointer<void> {
      return toPointer(lib.symbols.bufferGetAttributesPtr(p));
    },
    bufferGetBgPtr(p: Pointer<Buffer>): Pointer<void> {
      return toPointer(lib.symbols.bufferGetBgPtr(p));
    },
    bufferGetCharPtr(p: Pointer<Buffer>): Pointer<void> {
      return toPointer(lib.symbols.bufferGetCharPtr(p));
    },
    bufferGetFgPtr(p: Pointer<Buffer>): Pointer<void> {
      return toPointer(lib.symbols.bufferGetFgPtr(p));
    },
    bufferRealCharSize(p: Pointer<Buffer>, addLineBreaks: boolean): number {
      return lib.symbols.bufferRealCharSize(p, ffiBool(addLineBreaks));
    },
    bufferDrawBox(
      buf: Pointer<Buffer>,
      x: number,
      y: number,
      width: number,
      height: number,
      borderChars: Uint32Array,
      packedOptions: number,
      borderColor: RGBAInput,
      bgColor: RGBAInput
    ): void {
      lib.symbols.bufferDrawBox(
        buf,
        x,
        y,
        width,
        height,
        backend.ptr(borderChars),
        packedOptions,
        rgbaPtr(borderColor),
        rgbaPtr(bgColor)
      );
    },
    bufferDrawChar(
      buf: Pointer<Buffer>,
      codepoint: number,
      x: number,
      y: number,
      fg: RGBAInput,
      bg: RGBAInput,
      attributes: number
    ): void {
      lib.symbols.bufferDrawChar(
        buf,
        codepoint,
        x,
        y,
        rgbaPtr(fg),
        rgbaPtr(bg),
        attributes
      );
    },
    bufferDrawText(
      buf: Pointer<Buffer>,
      text: string,
      x: number,
      y: number,
      fg: RGBAInput,
      bg: RGBAInput,
      attributes: number
    ): void {
      const encoded = textEncoder.encode(text);
      lib.symbols.bufferDrawText(
        buf,
        backend.ptr(encoded),
        encoded.length,
        x,
        y,
        rgbaPtr(fg),
        rgbaPtr(bg),
        attributes
      );
    },
    bufferFillRect(
      buf: Pointer<Buffer>,
      x: number,
      y: number,
      width: number,
      height: number,
      bg: RGBAInput
    ): void {
      lib.symbols.bufferFillRect(buf, x, y, width, height, rgbaPtr(bg));
    },
    bufferWriteResolvedChars(
      p: Pointer<Buffer>,
      outPtr: Pointer<void>,
      len: number,
      addLineBreaks: boolean
    ): number {
      return lib.symbols.bufferWriteResolvedChars(
        p,
        outPtr,
        len,
        ffiBool(addLineBreaks)
      );
    },
    bufferClear(p: Pointer<Buffer>, bg: RGBAInput): void {
      lib.symbols.bufferClear(p, rgbaPtr(bg));
    },
  },
  renderer: {
    clearOutput(p: Pointer<Renderer>): void {
      lib.symbols.clearOutput(p);
    },
    disableMouse(p: Pointer<Renderer>): void {
      lib.symbols.disableMouse(p);
    },
    enableMouse(p: Pointer<Renderer>, enableMovement: boolean): void {
      lib.symbols.enableMouse(p, ffiBool(enableMovement));
    },
    getMousePointerStyle(p: Pointer<Renderer>): Pointer<void> {
      return toPointer(lib.symbols.getMousePointerStyle(p));
    },
    height(p: Pointer<Renderer>): number {
      return lib.symbols.height(p);
    },
    hitGridAdd(
      p: Pointer<Renderer>,
      x: number,
      y: number,
      width: number,
      height: number,
      id: number
    ): void {
      lib.symbols.hitGridAdd(p, x, y, width, height, id);
    },
    hitGridCheckHit(p: Pointer<Renderer>, x: number, y: number): number {
      return lib.symbols.hitGridCheckHit(p, x, y);
    },
    hitGridClear(p: Pointer<Renderer>): void {
      lib.symbols.hitGridClear(p);
    },
    hitGridClearDirty(p: Pointer<Renderer>): void {
      lib.symbols.hitGridClearDirty(p);
    },
    hitGridClearScissorRects(p: Pointer<Renderer>): void {
      lib.symbols.hitGridClearScissorRects(p);
    },
    hitGridIsDirty(p: Pointer<Renderer>): boolean {
      return lib.symbols.hitGridIsDirty(p);
    },
    hitGridPopScissorRect(p: Pointer<Renderer>): void {
      lib.symbols.hitGridPopScissorRect(p);
    },
    hitGridPushScissorRect(
      p: Pointer<Renderer>,
      x: number,
      y: number,
      w: number,
      h: number
    ): void {
      lib.symbols.hitGridPushScissorRect(p, x, y, w, h);
    },
    processEvents(p: Pointer<Renderer>): number {
      return lib.symbols.processEvents(p);
    },
    resizeRenderer(p: Pointer<Renderer>, width: number, height: number): void {
      lib.symbols.resizeRenderer(p, width, height);
    },
    setCursorPosition(
      p: Pointer<Renderer>,
      x: number,
      y: number,
      visible: boolean
    ): void {
      lib.symbols.setCursorPosition(p, x, y, ffiBool(visible));
    },
    setEventCallback(p: Pointer<Renderer>, cb: Pointer<void>): void {
      lib.symbols.setEventCallback(p, cb);
    },
    setMouseCallback(p: Pointer<Renderer>, cb: Pointer<void>): void {
      lib.symbols.setMouseCallback(p, cb);
    },
    setMousePointerStyle(p: Pointer<Renderer>, style: Pointer<void>): void {
      lib.symbols.setMousePointerStyle(p, style);
    },
    setResizeCallback(p: Pointer<Renderer>, cb: Pointer<void>): void {
      lib.symbols.setResizeCallback(p, cb);
    },
    width(p: Pointer<Renderer>): number {
      return lib.symbols.width(p);
    },
    createRenderer(
      width: number,
      height: number,
      testMode: boolean
    ): Pointer<Renderer> {
      return toPointer(
        lib.symbols.createRenderer(width, height, ffiBool(testMode))
      );
    },
    destroyRenderer(p: Pointer<Renderer>): number {
      return lib.symbols.destroyRenderer(p);
    },
    getCapabilities(p: Pointer<Renderer>): {
      rgb: boolean;
      ansi256: boolean;
      ansi16: boolean;
    } {
      const caps = lib.symbols.getCapabilities(p);
      return {
        rgb: caps[0] !== 0,
        ansi256: caps[1] !== 0,
        ansi16: caps[2] !== 0,
      };
    },
    getCapturedOutput(
      p: Pointer<Renderer>,
      outPtr: Pointer<void>
    ): Pointer<void> {
      return toPointer(lib.symbols.getCapturedOutput(p, outPtr));
    },
    getCurrentBuffer(p: Pointer<Renderer>): Pointer<Buffer> {
      return toPointer(lib.symbols.getCurrentBuffer(p));
    },
    getNextBuffer(p: Pointer<Renderer>): Pointer<Buffer> {
      return toPointer(lib.symbols.getNextBuffer(p));
    },
    getRenderStats(p: Pointer<Renderer>): {
      lastFrameTimeMs: number;
      averageFrameTimeMs: number;
      frameCount: number;
      cellsUpdated: number;
      averageCellsUpdated: number;
      renderTimeUs: number;
      stdoutWriteTimeUs: number;
    } {
      const buf = new Uint8Array(56);
      const bufPtr = backend.ptr(buf);
      lib.symbols.getRenderStats(p, bufPtr);
      const view = new DataView(buf.buffer);
      return {
        lastFrameTimeMs: view.getFloat64(0, true),
        averageFrameTimeMs: view.getFloat64(8, true),
        frameCount: Number(view.getBigUint64(16, true)),
        cellsUpdated: view.getUint32(24, true),
        averageCellsUpdated: view.getUint32(28, true),
        renderTimeUs: view.getFloat64(32, true),
        stdoutWriteTimeUs: view.getFloat64(40, true),
      };
    },
    injectMouseEvent(
      p: Pointer<Renderer>,
      kind: string,
      button: number,
      x: number,
      y: number,
      ctrl: boolean,
      shift: boolean,
      alt: boolean,
      scrollDir: number
    ): void {
      const kindBuf = new TextEncoder().encode(kind);
      lib.symbols.injectMouseEvent(
        p,
        kindBuf,
        BigInt(kindBuf.byteLength),
        button,
        x,
        y,
        ctrl,
        shift,
        alt,
        scrollDir
      );
    },
    injectResizeEvent(
      p: Pointer<Renderer>,
      width: number,
      height: number
    ): void {
      lib.symbols.injectResizeEvent(p, width, height);
    },
    render(p: Pointer<Renderer>, force: boolean): number {
      return lib.symbols.render(p, ffiBool(force));
    },
  },
  terminal: {
    getTerminalSize(): { width: number; height: number } {
      const size = normalizeU64(lib.symbols.getTerminalSize());
      return {
        // biome-ignore lint/suspicious/noBitwiseOperators: packed u64 terminal size
        width: Number((size >> 32n) & 0xffffffffn),
        // biome-ignore lint/suspicious/noBitwiseOperators: packed u64 terminal size
        height: Number(size & 0xffffffffn),
      };
    },
    restoreTerminal(p: Pointer<Renderer>): number {
      return lib.symbols.restoreTerminal(p);
    },
    setupTerminal(
      p: Pointer<Renderer>,
      useAlternateScreen: boolean,
      enableMouse: boolean,
      enableMouseMovement: boolean
    ): number {
      return lib.symbols.setupTerminal(
        p,
        ffiBool(useAlternateScreen),
        ffiBool(enableMouse),
        ffiBool(enableMouseMovement)
      );
    },
  },
  events: {
    setEventCallback(
      p: Pointer<Renderer>,
      callbackPtr: Pointer<Renderer> | 0
    ): void {
      lib.symbols.setEventCallback(p, callbackPtr);
    },
    setResizeCallback(
      p: Pointer<Renderer>,
      callbackPtr: Pointer<Renderer> | 0
    ): void {
      lib.symbols.setResizeCallback(p, callbackPtr);
    },
    createEventCallback(
      handler: (event: {
        key: string;
        ctrl: boolean;
        shift: boolean;
        alt: boolean;
      }) => void
    ): import("./platform/types").FFICallbackInstance {
      return lib.createCallback(
        (
          typePtr: number,
          typeLen: bigint,
          keyPtr: number,
          keyLen: bigint,
          ctrl: boolean,
          shift: boolean,
          alt: boolean
        ) => {
          const tLen = Number(typeLen);
          const kLen = Number(keyLen);
          if (!typePtr || tLen === 0 || !keyPtr || kLen === 0) {
            return;
          }
          const type = new TextDecoder().decode(
            backend.toArrayBuffer(backend.toPointer<void>(typePtr), 0, tLen)
          );
          const key = new TextDecoder().decode(
            backend.toArrayBuffer(backend.toPointer<void>(keyPtr), 0, kLen)
          );
          if (type !== "key") {
            return;
          }
          queueMicrotask(() => {
            handler({ key, ctrl, shift, alt });
          });
        },
        {
          args: [
            FFIType.ptr,
            FFIType.u64,
            FFIType.ptr,
            FFIType.u64,
            FFIType.bool,
            FFIType.bool,
            FFIType.bool,
          ],
          returns: FFIType.void,
        }
      );
    },
    createResizeCallback(
      handler: (event: { width: number; height: number }) => void
    ): import("./platform/types").FFICallbackInstance {
      return lib.createCallback(
        (width: number, height: number) => {
          queueMicrotask(() => {
            handler({ width, height });
          });
        },
        { args: [FFIType.u32, FFIType.u32], returns: FFIType.void }
      );
    },
    createMouseCallback(
      handler: (event: {
        kind: string;
        button: number;
        x: number;
        y: number;
        ctrl: boolean;
        shift: boolean;
        alt: boolean;
        scrollDir: number;
      }) => void
    ): import("./platform/types").FFICallbackInstance {
      return lib.createCallback(
        (
          typePtr: number,
          typeLen: bigint,
          kindPtr: number,
          kindLen: bigint,
          button: number,
          x: number,
          y: number,
          ctrl: boolean,
          shift: boolean,
          alt: boolean,
          scrollDir: number
        ) => {
          const tLen = Number(typeLen);
          const kLen = Number(kindLen);
          if (!typePtr || tLen === 0 || !kindPtr || kLen === 0) {
            return;
          }
          const type = new TextDecoder().decode(
            backend.toArrayBuffer(backend.toPointer<void>(typePtr), 0, tLen)
          );
          const kind = new TextDecoder().decode(
            backend.toArrayBuffer(backend.toPointer<void>(kindPtr), 0, kLen)
          );
          if (type !== "mouse") {
            return;
          }
          queueMicrotask(() => {
            handler({ kind, button, x, y, ctrl, shift, alt, scrollDir });
          });
        },
        {
          args: [
            FFIType.ptr,
            FFIType.u64,
            FFIType.ptr,
            FFIType.u64,
            FFIType.u32,
            FFIType.u32,
            FFIType.u32,
            FFIType.bool,
            FFIType.bool,
            FFIType.bool,
            FFIType.u32,
          ],
          returns: FFIType.void,
        }
      );
    },
    setMouseCallback(
      p: Pointer<Renderer>,
      callbackPtr: Pointer<Renderer> | 0
    ): void {
      lib.symbols.setMouseCallback(p, callbackPtr);
    },
  },
};

// biome-ignore lint/suspicious/noExplicitAny: converts bun:ffi Pointer to branded Pointer<T>
export function asPtr<T>(p: any): Pointer<T> {
  return p as unknown as Pointer<T>;
}
