// AUTO-GENERATED by scripts/generate-ffi.ts — DO NOT EDIT
// Source: target/moontui-schema.json

export const FrameStatsStruct = {
  repr: "C",
  fields: [
    {
      name: "last_frame_time_ms",
      type: "f64",
      offset: 0,
    },
    {
      name: "average_frame_time_ms",
      type: "f64",
      offset: 8,
    },
    {
      name: "frame_count",
      type: "u64",
      offset: 16,
    },
    {
      name: "cells_updated",
      type: "u32",
      offset: 24,
    },
    {
      name: "average_cells_updated",
      type: "u32",
      offset: 28,
    },
    {
      name: "render_time_us",
      type: "f64",
      offset: 32,
    },
    {
      name: "stdout_write_time_us",
      type: "f64",
      offset: 40,
    },
    {
      name: "render_time_valid",
      type: "bool",
      offset: 48,
    },
    {
      name: "stdout_write_time_valid",
      type: "bool",
      offset: 49,
    },
  ],
  size: 56,
  alignment: 8,
} as const;
