import { execSync } from "node:child_process";
import {
  existsSync,
  readFileSync,
  renameSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { basename, join, relative } from "node:path";

interface SchemaParam {
  name: string;
  pointer_mutability?: "mutable" | "readonly";
  role: string;
  type: string;
}

interface SchemaStructField {
  name: string;
  offset: number;
  type: string;
}

interface SchemaStruct {
  alignment: number;
  fields: SchemaStructField[];
  repr: string;
  size: number;
}

interface SchemaCallback {
  ffi_args: string[];
  handler_body: string;
  handler_params: string;
  handler_type: string;
  name: string;
}

interface SchemaFunction {
  api_group: "buffer" | "renderer" | "terminal";
  ffi_name: string;
  manual?: boolean;
  output_struct?: string;
  params: SchemaParam[];
  receiver: string | null;
  returns: string;
  rust_name: string;
  ts_args?: string;
  ts_body?: string;
  ts_returns?: string;
}

interface Schema {
  callbacks?: Record<string, SchemaCallback>;
  functions: Record<string, SchemaFunction>;
  structs?: Record<string, SchemaStruct>;
}

const FFI_TYPE_MAP: Record<string, string> = {
  void: "FFIType.void",
  bool: "FFIType.bool",
  u8: "FFIType.u8",
  i8: "FFIType.i8",
  u16: "FFIType.u16",
  i16: "FFIType.i16",
  u32: "FFIType.u32",
  i32: "FFIType.i32",
  u64: "FFIType.u64",
  usize: "FFIType.u64",
  i64: "FFIType.i64",
  f32: "FFIType.f32",
  f64: "FFIType.f64",
  ptr: "FFIType.ptr",
};

const TS_TYPE_MAP: Record<string, string> = {
  void: "void",
  bool: "boolean",
  u8: "number",
  i8: "number",
  u16: "number",
  i16: "number",
  u32: "number",
  i32: "number",
  u64: "bigint",
  usize: "bigint",
  i64: "bigint",
  f32: "number",
  f64: "number",
  ptr: "Pointer<void>",
};

function snakeToCamel(s: string): string {
  return s.replace(/_([a-z])/g, (_, c) => c.toUpperCase());
}

function resolveFfiType(type: string, context: string): string {
  const mapped = FFI_TYPE_MAP[type];
  if (!mapped) {
    throw new Error(`Unknown FFI type "${type}" in ${context}`);
  }
  return mapped;
}

function resolveTsType(type: string, context: string): string {
  const mapped = TS_TYPE_MAP[type];
  if (!mapped) {
    throw new Error(`Unknown TS type "${type}" in ${context}`);
  }
  return mapped;
}

function emitCallbackFactory(desc: SchemaCallback, indent: string): string {
  let content = "";
  content += `${indent}  handler: ${desc.handler_type}\n`;
  content += `${indent}): import("./platform/types").FFICallbackInstance {\n`;
  content += `${indent}  return lib.createCallback(\n`;
  content += `${indent}    (${desc.handler_params}) => {\n`;
  for (const line of desc.handler_body.split("\n")) {
    content += `${indent}      ${line}\n`;
  }
  content += `${indent}    },\n`;
  const ffiArgs = desc.ffi_args.map((type) =>
    resolveFfiType(type, `${desc.name}:callback`)
  );
  content += `${indent}    { args: [${ffiArgs.join(", ")}], returns: FFIType.void }\n`;
  content += `${indent}  )\n`;
  content += `${indent}},\n`;
  return content;
}

function main(): void {
  const schemaPath = join(
    import.meta.dirname,
    "..",
    "target",
    "moontui-schema.json"
  );
  if (!existsSync(schemaPath)) {
    console.error("Schema file not found. Run `cargo build` first.");
    process.exit(1);
  }
  const schema: Schema = JSON.parse(readFileSync(schemaPath, "utf8"));
  generateFfiTs(schema);
}

function generateFfiTs(schema: Schema): string[] {
  const functions = Object.entries(schema.functions);
  const manualFns = functions.filter(([, fn]) => fn.manual);
  const generatedFns = functions.filter(([, fn]) => !fn.manual);
  const callbacks = requiredCallbacks(schema.callbacks ?? {});

  const groups = new Map<string, [string, SchemaFunction][]>();
  for (const [name, fn] of generatedFns) {
    const key = fn.receiver ?? "Static";
    if (!groups.has(key)) {
      groups.set(key, []);
    }
    groups.get(key)?.push([name, fn]);
  }

  let ffiContent = `// AUTO-GENERATED by scripts/generate-ffi.ts — DO NOT EDIT
// Source: target/moontui-schema.json

import { backend, FFIType, ffiBool, type MutablePointer, type Pointer, type ReadonlyPointer } from "./platform/index"
import { type RGBAInput, toRGBA } from "./rgba"

export type { MutablePointer, Pointer, ReadonlyPointer } from "./platform/index"

const libPath = backend.resolveLibraryPath()

// biome-ignore lint/complexity/noBannedTypes: opaque handle type for FFI branding
export type Renderer = {}
// biome-ignore lint/complexity/noBannedTypes: opaque handle type for FFI branding
export type Buffer = {}

function toPointer<T>(value: number | bigint): Pointer<T> {
  return backend.toPointer<T>(value)
}

function normalizeU64(value: number | bigint): bigint {
  return typeof value === "bigint" ? value : BigInt(value)
}

const lib = backend.loadLibrary(libPath, {
`;

  // Add manual FFI function lib definitions from schema
  ffiContent += "  // --- Manual FFI functions (/// @ffi_manual) ---\n";
  for (const [, fn] of manualFns) {
    const args = fn.params.map((p) =>
      resolveFfiType(p.type, `${fn.ffi_name}:${p.name}`)
    );
    const returns = resolveFfiType(fn.returns, `${fn.ffi_name}:returns`);
    ffiContent += `  ${fn.ffi_name}: { args: [${args.join(", ")}], returns: ${returns} },\n`;
  }

  for (const [receiver, fns] of groups) {
    ffiContent += `  // --- ${receiver} ---\n`;
    for (const [, fn] of fns) {
      const args = fn.params.map((p) =>
        resolveFfiType(p.type, `${fn.ffi_name}:${p.name}`)
      );
      const returns = resolveFfiType(fn.returns, `${fn.ffi_name}:returns`);
      ffiContent += `  ${fn.ffi_name}: { args: [${args.join(", ")}], returns: ${returns} },\n`;
    }
    ffiContent += "\n";
  }

  ffiContent += `})

const textEncoder = new TextEncoder()
const textDecoder = new TextDecoder()

function decodeStringPointer(ptr: number, len: number): string {
  return textDecoder.decode(backend.toArrayBuffer(backend.toPointer<void>(ptr), 0, len))
}

function rgbaPtr(color: RGBAInput): Pointer<void> {
  const rgba = toRGBA(color)
  return backend.ptr(rgba.buffer)
}

// Categorize functions into sub-groups
`;

  // Build sub-groups
  const bufferFns: SchemaFunction[] = [];
  const rendererFns: SchemaFunction[] = [];
  const terminalFns: SchemaFunction[] = [];

  for (const [, fns] of groups) {
    for (const [, fn] of fns) {
      pushApiFunction(fn, bufferFns, rendererFns, terminalFns);
    }
  }

  for (const [, fn] of manualFns) {
    pushApiFunction(fn, bufferFns, rendererFns, terminalFns);
  }

  ffiContent += "export const api = {\n";
  ffiContent += "  buffer: {\n";
  ffiContent += generateApiFunctions(bufferFns, "    ");
  ffiContent += "  },\n";
  ffiContent += "  renderer: {\n";
  ffiContent += generateApiFunctions(rendererFns, "    ");
  ffiContent += "  },\n";
  ffiContent += "  terminal: {\n";
  ffiContent += generateApiFunctions(terminalFns, "    ");
  ffiContent += "  },\n";
  ffiContent += "  events: {\n";
  ffiContent += "    setEventCallback(\n";
  ffiContent += "      p: Pointer<Renderer>,\n";
  ffiContent += "      callbackPtr: Pointer<void> | 0\n";
  ffiContent += "    ): void {\n";
  ffiContent += "      lib.symbols.setEventCallback(p, callbackPtr)\n";
  ffiContent += "    },\n";
  ffiContent += "    setResizeCallback(\n";
  ffiContent += "      p: Pointer<Renderer>,\n";
  ffiContent += "      callbackPtr: Pointer<void> | 0\n";
  ffiContent += "    ): void {\n";
  ffiContent += "      lib.symbols.setResizeCallback(p, callbackPtr)\n";
  ffiContent += "    },\n";
  ffiContent += "    createEventCallback(\n";
  ffiContent += emitCallbackFactory(callbacks.event, "    ");
  ffiContent += "    createResizeCallback(\n";
  ffiContent += emitCallbackFactory(callbacks.resize, "    ");
  ffiContent += "    createMouseCallback(\n";
  ffiContent += emitCallbackFactory(callbacks.mouse, "    ");
  ffiContent += "    setMouseCallback(\n";
  ffiContent += "      p: Pointer<Renderer>,\n";
  ffiContent += "      callbackPtr: Pointer<void> | 0\n";
  ffiContent += "    ): void {\n";
  ffiContent += "      lib.symbols.setMouseCallback(p, callbackPtr)\n";
  ffiContent += "    },\n";
  ffiContent += "  },\n";
  ffiContent += "}\n\n";
  ffiContent +=
    "// biome-ignore lint/suspicious/noExplicitAny: converts bun:ffi Pointer to branded Pointer<T>\n";
  ffiContent += "export function asPtr<T>(p: any): Pointer<T> {\n";
  ffiContent += "  return p as unknown as Pointer<T>\n";
  ffiContent += "}\n";

  const outputPath = join(
    import.meta.dirname,
    "..",
    "packages",
    "core",
    "src",
    "ffi.ts"
  );
  writeGeneratedFile(outputPath, ffiContent);
  console.log(`Generated ${outputPath}`);
  const structsPath = join(
    import.meta.dirname,
    "..",
    "packages",
    "core",
    "src",
    "structs.ts"
  );
  writeGeneratedFile(structsPath, generateStructsTs(schema.structs ?? {}));
  console.log(`Generated ${structsPath}`);
  return [outputPath, structsPath];
}

function pushApiFunction(
  fn: SchemaFunction,
  bufferFns: SchemaFunction[],
  rendererFns: SchemaFunction[],
  terminalFns: SchemaFunction[]
): void {
  switch (fn.api_group) {
    case "buffer":
      bufferFns.push(fn);
      return;
    case "renderer":
      rendererFns.push(fn);
      return;
    case "terminal":
      terminalFns.push(fn);
      return;
    default:
      throw new Error(`Unknown API group "${fn.api_group}" for ${fn.ffi_name}`);
  }
}

function requiredCallbacks(callbacks: Record<string, SchemaCallback>): {
  event: SchemaCallback;
  mouse: SchemaCallback;
  resize: SchemaCallback;
} {
  const { event, mouse, resize } = callbacks;
  if (!(event && mouse && resize)) {
    throw new Error("Schema is missing required callback descriptors");
  }
  return { event, mouse, resize };
}

function writeGeneratedFile(outputPath: string, content: string): void {
  const root = join(import.meta.dirname, "..");
  const tmpPath = join(
    dirnameCompat(outputPath),
    `.${basename(outputPath)}.${process.pid}.tmp.ts`
  );
  try {
    writeFileSync(tmpPath, content, "utf8");
    execSync(`bunx biome format --write ${relative(root, tmpPath)}`, {
      cwd: root,
      stdio: "inherit",
    });
    renameSync(tmpPath, outputPath);
  } catch (error) {
    rmSync(tmpPath, { force: true });
    throw error;
  }
}

function dirnameCompat(path: string): string {
  return path.slice(0, Math.max(path.lastIndexOf("/"), path.lastIndexOf("\\")));
}

function generateStructsTs(structs: Record<string, SchemaStruct>): string {
  let content = `// AUTO-GENERATED by scripts/generate-ffi.ts — DO NOT EDIT
// Source: target/moontui-schema.json

`;
  for (const [name, struct] of Object.entries(structs)) {
    content += `export const ${name}Struct = ${JSON.stringify(struct, null, 2)} as const\n\n`;
  }
  return content;
}

// biome-ignore lint/complexity/noExcessiveCognitiveComplexity: build script complexity is acceptable
function generateApiFunctions(fns: SchemaFunction[], indent: string): string {
  let content = "";
  for (const fn of fns) {
    const outputWrapper = emitOutputStructWrapper(fn, indent);
    if (outputWrapper) {
      content += outputWrapper;
    } else if (fn.manual && fn.ts_body) {
      const tsArgs = fn.ts_args ?? "";
      const tsReturns = fn.ts_returns ?? "void";
      content += `${indent}${fn.ffi_name}(${tsArgs}): ${tsReturns} {\n`;
      const body = fn.ts_body.replace(/\\n/g, "\n");
      for (const line of body.split("\n")) {
        content += `${indent}  ${line}\n`;
      }
      content += `${indent}},\n`;
    } else {
      const nonSelfParams = fn.params.filter((p) => p.role !== "self");
      const paramList = nonSelfParams.map((p) => {
        const paramName = snakeToCamel(p.name);
        const paramType = resolveTsType(p.type, `${fn.ffi_name}:${p.name}`);
        return `${paramName}: ${paramType}`;
      });
      const returnType = resolveReturnType(fn);
      if (fn.receiver !== null) {
        const typeName =
          fn.receiver === "OptimizedBuffer" ? "Buffer" : "Renderer";
        paramList.unshift(`p: Pointer<${typeName}>`);
      }
      const callArgs = fn.params.map((p) => {
        if (p.role === "self") {
          return "p";
        }
        if (p.type === "bool") {
          return `ffiBool(${snakeToCamel(p.name)})`;
        }
        return snakeToCamel(p.name);
      });
      content += `${indent}${fn.ffi_name}(${paramList.join(", ")}): ${returnType} {\n`;
      if (fn.returns === "ptr") {
        const cast = pointerReturnCast(fn);
        content += `${indent}  return toPointer(lib.symbols.${fn.ffi_name}(${callArgs.join(", ")}))${cast}\n`;
      } else if (fn.returns === "void") {
        content += `${indent}  lib.symbols.${fn.ffi_name}(${callArgs.join(", ")});\n`;
      } else {
        content += `${indent}  return lib.symbols.${fn.ffi_name}(${callArgs.join(", ")})\n`;
      }
      content += `${indent}},\n`;
    }
  }
  return content;
}

function pointerReturnCast(fn: SchemaFunction): string {
  if (fn.ffi_name === "getCurrentBuffer") {
    return " as ReadonlyPointer<Buffer>";
  }
  if (fn.ffi_name === "getNextBuffer") {
    return " as MutablePointer<Buffer>";
  }
  return "";
}

function emitOutputStructWrapper(
  fn: SchemaFunction,
  indent: string
): string | null {
  if (fn.output_struct === "Capabilities") {
    return `${indent}${fn.ffi_name}(p: Pointer<Renderer>): { rgb: boolean; ansi256: boolean; ansi16: boolean } {\n${indent}  const buf = new Uint8Array(3)\n${indent}  lib.symbols.${fn.ffi_name}(p, backend.ptr(buf))\n${indent}  return { rgb: buf[0] !== 0, ansi256: buf[1] !== 0, ansi16: buf[2] !== 0 }\n${indent}},\n`;
  }
  if (fn.output_struct === "FrameStats") {
    return `${indent}${fn.ffi_name}(p: Pointer<Renderer>): { lastFrameTimeMs: number; averageFrameTimeMs: number; frameCount: number; cellsUpdated: number; averageCellsUpdated: number; renderTimeUs: number; stdoutWriteTimeUs: number } {\n${indent}  const buf = new Uint8Array(56)\n${indent}  const bufPtr = backend.ptr(buf)\n${indent}  lib.symbols.${fn.ffi_name}(p, bufPtr)\n${indent}  const view = new DataView(buf.buffer)\n${indent}  return {\n${indent}    lastFrameTimeMs: view.getFloat64(0, true),\n${indent}    averageFrameTimeMs: view.getFloat64(8, true),\n${indent}    frameCount: Number(view.getBigUint64(16, true)),\n${indent}    cellsUpdated: view.getUint32(24, true),\n${indent}    averageCellsUpdated: view.getUint32(28, true),\n${indent}    renderTimeUs: view.getFloat64(32, true),\n${indent}    stdoutWriteTimeUs: view.getFloat64(40, true),\n${indent}  }\n${indent}},\n`;
  }
  return null;
}

function resolveReturnType(fn: SchemaFunction): string {
  if (fn.ffi_name === "getCurrentBuffer") {
    return "ReadonlyPointer<Buffer>";
  }
  if (fn.ffi_name === "getNextBuffer") {
    return "MutablePointer<Buffer>";
  }
  return resolveTsType(fn.returns, `${fn.ffi_name}:returns`);
}

main();
